; PlatformIO Project Configuration File for STM32F103C8T6 (Blue Pill)
; https://docs.platformio.org/page/projectconf.html

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino

; Konfiguracja bibliotek i flag kompilatora (jeśli potrzebne)
build_flags = 
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON

; Opcje wgrywania za pomocą OpenOCD (lokalnego na RPi 5)
upload_protocol = custom
upload_command = openocd -f firmware/bluepill/openocd.cfg -c "program $SOURCE verify reset exit"
